### ISSUE TITLE
Shut Down Windows Dialog not appearing properly

### ISSUE THREAD

**Issue by Cyhnk** [hanyizhao/NetSpeedMonitor#10]
Hello, while NetSpeedMonitor is running, Shut Down Windows dialog not appearing properly when I press Alt+F4 on desktop, appearing but closing at the same second. It's working fine when I exit from NetSpeedMonitor. I'm using Windows 10 x64 btw if needed.

**Comment by hanyizhao** [comment]
Sorry guy, it works fine in my PC. This bug can not be reproduced now.
Is it possible if you are holding Alt+F4?
![alt f4](https://user-images.githubusercontent.com/3882569/40590399-a833193e-6230-11e8-8116-0c67bbbf1397.gif)

**Comment by Cyhnk** [comment]
Working fine with the latest update currently, thank you for your time.
